[package]
name = "dawn-process-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
color-eyre = "0.6.3"
crossterm = "0.29.0"
toml = "1.0.3"
serde = { version =  "1.0.228",  features = ["derive"]  }
